services:
  - type: web
    name: telecal-backend
    runtime: node
    buildCommand: npm install && npm run build --workspace=packages/shared && npx prisma generate --prefix=apps/server && npm run build --workspace=apps/server && npx prisma migrate deploy --prefix=apps/server
    startCommand: node apps/server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000