services:
  - type: web
    name: telecal-backend
    runtime: node
    rootDir: apps/server
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000